---

- name: Remove old configurations
  shell: /bin/rm -rf /etc/nginx/conf.d/*.conf
  sudo: yes

- name: Apply master nginx template
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  sudo: yes

- name: Apply docker nginx template
  template: src=catalog.conf.j2 dest=/etc/nginx/conf.d/catalog.conf
  sudo: yes

