---
- name: Check for NetCDF
  stat: path=/usr/local/bin/ncdump
  register: nc

- include: netcdf_amazon.yml
  when: nc.stat.exists == False and ansible_distribution == "Amazon"

- include: netcdf_centos.yml
  when: nc.stat.exists == False and (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
