---

- name: Install HDF5 MPI dependencies
  yum: name={{ item }} state=present
  sudo: yes
  with_items:
    - openmpi-devel.x86_64

- name: Install HDF5 from source
  get_url: url=http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.15-patch1/src/hdf5-1.8.15-patch1.tar.bz2 dest=/tmp/hdf5-1.8.15-patch1.tar.bz2 force=no

- name: Extract HDF5 Source Code
  command: /bin/tar -jxvf /tmp/hdf5-1.8.15-patch1.tar.bz2 chdir=/usr/local/src creates=/usr/local/src/hdf5-1.8.15-patch1/configure
  sudo: yes

- name: Make and install HDF5
  shell: ./configure --prefix=/usr && /usr/bin/make && /usr/bin/make check && /usr/bin/make install chdir=/usr/local/src/hdf5-1.8.15-patch1
  sudo: yes

- name: Download NetCDF4 Source Code
  get_url: url=ftp://ftp.unidata.ucar.edu/pub/netcdf/old/netcdf-4.3.2.tar.gz dest=/tmp/netcdf-4.3.2.tar.gz force=no

- name: Extract NetCDF4 Source Code
  command: /bin/tar -zxvf /tmp/netcdf-4.3.2.tar.gz chdir=/usr/local/src creates=/usr/local/src/netcdf-4.3.2/configure
  sudo: yes

- name: Make and install netcdf
  shell: ./configure --prefix=/usr/local --enable-netcdf-4 --enable-dap --enable-shared && /usr/bin/make && /usr/bin/make install chdir=/usr/local/src/netcdf-4.3.2/ creates=/usr/local/bin/ncdump
  sudo: yes
