---

- name: Install EPEL
  yum: name={{ item }} state=present
  sudo: yes
  with_items:
    - epel-release
  when: ansible_distribution == "CentOS"

- name: Add SELinux Utilities
  yum: name={{ item }} state=present
  sudo: yes
  with_items:
    - policycoreutils-python
  when: ansible_distribution == "CentOS"

- name: Add pip
  yum: name={{ item }} state=present
  sudo: yes
  with_items:
    - python-pip
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
